config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :offers, only: %i[index new create show edit update destroy] do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index]

  resources :contacts, only: :index
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :offers
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_offer, only: %i[new create]

  def index
    # Offers that the current user has made and have been booked by others
    @my_offers_booked_by_others = current_user.offers.joins(:bookings).distinct

    # Offers that the current user has booked
    @my_booked_offers = current_user.bookings.includes(:offer).map(&:offer)
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.offer = @offer
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: 'Booking was successful!'
    else
      render :new
    end
  end

  def show
  end

  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

  def booking_params
    params.require(:booking).permit(:offer_id, :check_in, :check_out)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @offers = Offer.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @offers = Offer.all
    end
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user

    if params[:offer][:photo].present?
      uploaded_file = params[:offer][:photo]
      cloudinary_file = Cloudinary::Uploader.upload(uploaded_file.path)
      @offer.image_url = cloudinary_file['url']
    end

    if @offer.save
      redirect_to offer_path(@offer), notice: 'Offer was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to offers_path, status: :see_other
  end

  def update
    @offer.update(offer_params)
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :edit
    end
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:name, :description, :address, :price, :photo, :image_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="booking-index">

<div class="grid-container">
  <div class="grid-column"> <%#=A start %>
    <h1 class="card-name-pink">My booked offers</h1> <%#=A.1 start  and end, class=text-section%>
    <ul class="cards-section"> <%#=A.2 start%>
      <% if @my_offers_booked_by_others.any? %>
          <% @my_offers_booked_by_others.each do |offer| %>
            <div class="booking-modelcard">
              <li>
                <h3 class="card-name"><%= offer.name %></h3>
                <div>
                  <% if offer.photo.attached? %>
                  <%= cl_image_tag offer.photo.key, class: "card-image", height: 110,  crop: :fill %>
                  <% else %>
                  <%= image_tag "train.jpg", alt: "train", width: 200 %>
                  <% end %>
                </div>
                <div class="card-text">
                Booked by:
                <ul class="booking-text">
                  <% offer.bookings.each do |booking| %>
                    <li>
                      <%= booking.user.email %>
                      From: <%= booking.check_in.strftime("%B %d, %Y") %>
                      Until: <%= booking.check_out.strftime("%B %d, %Y") %>
                    </li>
                  <% end %>
                </ul>
                </div>
              </li>
            </div>
          <% end %>
      <% else %>
        <p>No one is interested in your bad experience yet</p>
      <% end %>
    </ul> <%#=A.2 end%>
  </div> <%#=A end %>

  <div class="grid-column">
    <h1 class="card-name-pink">Offers I booked</h1>
    <ul class="cards-section">
      <% if @my_booked_offers.any? %>
          <% @my_booked_offers.each do |offer| %>
          <div class="card-model">
            <li><h3 class="card-name"><%= offer.name %></h3>
            <div>
              <% if offer.photo.attached? %>
              <%= cl_image_tag offer.photo.key, class: "card-image", height: 110,  crop: :fill %>
              <% else %>
              <%= image_tag "train.jpg", alt: "train", width: 200 %>
              <% end %>
            </div>
            </li>
          </div>
          <% end %>
      <% else %>
      <p>You are not interested in any bad experience yet.</p>
    <% end %>
    </ul>
  </div>

</div>

  </div>

app/views/bookings/new.html.erb
<h1>Book <%= @offer.name %></h1>
<div class="new-booking">
  <%= simple_form_for [@offer, @booking] do |f| %>
    <h3>When would you like to check in?</h3>
    <%= f.input :check_in, as: :string, input_html: { data: { controller: "datepicker" }} %>
    <h3>When would you like to check out?</h3>
    <%= f.input :check_out, as: :string, input_html: { data: { controller: "datepicker" }} %>
    <%= f.submit "Book now!", class: "btn btn-primary" %>
    <% end %>
</div>

 <%# use flatpickr gem!! %>

app/views/contacts/index.html.erb
<div class="show p-5">
  <h1 class="pb-5">Here is where you can find us:</h1>

  <p class="py-2">
    <a href="https://github.com/JCorts1" target="_blank"><i class="fa-brands fa-github"></i></a>
    Jay Cortes
  </p>
  <p class="py-2">
    <a href="https://github.com/sophiernh" target="_blank"><i class="fa-brands fa-github"></i></a>
    Sophie Ranaivoharisoa
  </p>
  <p class="py-2">
    <a href="https://github.com/Lukas-Bertram" target="_blank"><i class="fa-brands fa-github"></i></a>
    Lukas Bertram
  </p>
  <p class="py-2">
    <a href="https://github.com/dariapauli" target="_blank"><i class="fa-brands fa-github"></i></a>
    Rahel Pauli
  </p>
</div>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible show fade m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="p-5 bg-dark text-light">
    <div class="row">

      <div class="col-6 col-md-2 mb-3">
        <h3>BadBnB</h3>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="text-light nav-link p-0 text-body-secondary">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="text-light nav-link p-0 text-body-secondary">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="text-light nav-link p-0 text-body-secondary">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="text-light nav-link p-0 text-body-secondary">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="text-light nav-link p-0 text-body-secondary">About</a></li>
        </ul>
      </div>

      <div class="col-md-5 offset-md-1 mb-3">
        <form>
          <h5>Subscribe to our newsletter</h5>
          <p>Monthly digest of what's new and exciting from us.</p>
          <div class="d-flex flex-column flex-sm-row w-100 gap-2">
            <label for="newsletter1" class="visually-hidden">Email address</label>
            <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
            <button class="btn btn-primary" type="button">Subscribe</button>
          </div>
        </form>
      </div>
    </div>

    <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
      <p>© 2024 Neighborhood Network // Le Wagon.</p>
      <ul class="list-unstyled d-flex">
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
        <li class="ms-3"><a class="link-body-emphasis" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
      </ul>
    </div>
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">BadBnB</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="/offers/new">Rent out your Place!</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/offers">Find a horrible Place!</a>
        </li>
        <% if !current_user %>
          <li class="nav-item">
            <a class="nav-link" href="/users/sign_in" tabindex="-1" aria-disabled="true">Login</a>
          </li>
        <% end %>
        <% if current_user %>
          <li class="nav-item" >
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "logout" %>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link" href="/contacts" tabindex="-1" aria-disabled="true">Contact Us</a>
        </li>
      </ul>
      <form class="d-flex nav-form" action="<%= offers_path %>" method="get">
        <input class="form-control me-2 " type="search" placeholder="Horrible place" aria-label="Search" name="query">
        <button class="btn btn-primary btn-search" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>



<!-- OLD NAVBAR

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">BadBnB</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Rent your place!</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Find a Horrible place!</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Contact Us</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BadBnB</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bungee&family=Honk&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= render "layouts/flashes" %>
    <%= yield %>

    <%= render "layouts/footer"%>
  </body>
</html>

app/views/offers/edit.html.erb
<h2>Does your bad place need some change?</h2>

<%= simple_form_for(@offer) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :address %>
  <%= f.submit "Update change", class: "btn btn-primary" %>
<% end %>

app/views/offers/index.html.erb
<div class="index">
  <div class="banner">
    <h1>Our Horrible Experiences</h1>
  </div>
</div>

<div class="cards">
    <ul class="cards-ul">
      <% @offers.each do |offer| %>
      <div class="card-model">
        <li>
          <h3><%= link_to offer.name, offer_path(offer), class: "card-name" %></h3>
          <div>
            <% if offer.photo.attached? %>

            <%= cl_image_tag offer.photo.key, class: "card-image", height: 110,  crop: :fill %>
            <% else %>
            <%= image_tag "train.jpg", alt: "train", width: 200 %>
            <% end %>
          </div>
          <%= link_to offer.price, offer_path(offer), class: "card-price" %>
        </li>
      </div>
      <% end %>
    </ul>
</div>

app/views/offers/new.html.erb
<div class="form-new p-5">
  <h1>Create a new place to stay!</h1>

  <div class="new-offer">
    <%= simple_form_for @offer, html: { multipart: true } do |f| %>
      <%= f.input :name, { class: "label-dark" }%>
      <div>
        <%= f.input :description, as: :text, :input_html => { 'rows' => 20, 'cols' => 10 } %>
      </div>
      <%= f.input :address %>
      <%= f.input :price %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Create offer!", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/offers/show.html.erb
<div class="show-offer">
  <div class="card-show">
  <h1><%= @offer.name %></h1>
    <% if @offer.photo && @offer.photo.key %>
    <%= cl_image_tag @offer.photo.key, class: "show-image", crop: :fill %>
  <% else %>
    <%= image_tag "train.jpg", alt: "train", width: 200 %>
  <% end %>
  <p><%= @offer.description %></p>

  <h2>Location:</h2>
  <p><%= @offer.address %></p>
  <p class="show-price"><%= @offer.price %> €</p>

  <% if @offer.availability == true %>
    <p><%= @offer.name %> is available!</p>
  <% else %>
    <p><%= @offer.name %> is not available</p>
  <% end %>

  <button class="btn">
    <%= link_to "Book now!", new_offer_booking_path(@offer), class: "button-home" %>
  </button>


  <div class="owner-show">
    <% if @offer.user == current_user %>
      <%= link_to "Delete",
      offer_path(@offer),
      data: {turbo_method: :delete, turbo_confirm: "This offer is horrible. Are you sure that you want to delete?"}, class: "show-delete"%>
      <%= link_to "Update",
      edit_offer_path(@offer), class: "show-delete"%>
    <% end %>
  </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="body">
    <div class="cont">
      <div class="left-scard">
        <h1>BadBnb</h1>
        <h3>a really bad experience!</h3>
      </div>
      <div class="right-scard">
        <h3>Book a bad experience!</h3>
        <button class="btn btn-primary"><%= link_to "OMG!", offers_path, class: "button-home" %> </button>
        <h3>Rent your BadBnB!</h3>
        <button class="btn btn-primary"><%= link_to "Try Now!", new_offer_path, class: "button-home" %></button>
      </div>
    </div>
</div>